Repository He-is-A-Pirate/Cat-Tower, pull requests merged in 2024-06, with the labels that each got.

#12 Admin Check 기능
  src/main/kotlin/heispirate/cattower/domain/admin/dto/AdminRequestDTO.kt
  src/main/kotlin/heispirate/cattower/domain/admin/dto/AdminRequestDTOver1.kt
  src/main/kotlin/heispirate/cattower/domain/admin/dto/AdminResponseDTO.kt
  src/main/kotlin/heispirate/cattower/domain/admin/repository/AdminRepository.kt
  src/main/kotlin/heispirate/cattower/domain/admin/service/AdminService.kt
  src/main/kotlin/heispirate/cattower/domain/admin/service/AdminServiceImpl.kt
  src/main/kotlin/heispirate/cattower/domain/comment/model/Comment.kt
  src/main/kotlin/heispirate/cattower/domain/comment/model/SubComment.kt
  src/main/kotlin/heispirate/cattower/domain/mainUser/repository/MainUserRepository.kt
  src/main/kotlin/heispirate/cattower/domain/post/model/Post.kt
  src/main/kotlin/heispirate/cattower/domain/post/model/SubCategory.kt
  src/main/kotlin/heispirate/cattower/infra/category/Category.kt
  src/main/kotlin/heispirate/cattower/infra/category/CategoryInterface.kt
  src/test/kotlin/heispirate/cattower/adminTest/AdminRoleTest.kt
  src/test/kotlin/heispirate/cattower/adminTest/ChangeAdminTest.kt
Labels: :sparkles: feature, :white_check_mark: test

#14 application.yml 파일 생성
  .gitignore
  src/main/resources/application.yml
Labels: :wrench: setting

#16 Feature/#15/sms
  build.gradle.kts
  src/main/kotlin/heispirate/cattower/domain/sms/controller/SMSController.kt
  src/main/kotlin/heispirate/cattower/domain/sms/dto/SendSMSRequestDTO.kt
  src/main/kotlin/heispirate/cattower/domain/sms/model/SMS.kt
  src/main/kotlin/heispirate/cattower/domain/sms/repository/SMSRepository.kt
  src/main/kotlin/heispirate/cattower/domain/sms/service/SMSService.kt
  src/main/kotlin/heispirate/cattower/domain/sms/service/SMSServiceImpl.kt
  src/main/kotlin/heispirate/cattower/infra/sms/SmsConfig.kt
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: :sparkles: feature

#19 인증코드 발송/ 확인 / 삭제 기능
  build.gradle.kts
  src/main/kotlin/heispirate/cattower/CatTowerApplication.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/controller/AuthCodeController.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/dto/AuthCodeRequestDTO.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/dto/AuthResponseDTO.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/model/AuthCode.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/repository/AuthCodeRepository.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/repository/CustomAuthCodeRepository.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/repository/CustomAuthCodeRepositoryImpl.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/service/AuthCodeService.kt
  src/main/kotlin/heispirate/cattower/domain/authCode/service/AuthCodeServiceImpl.kt
  src/main/kotlin/heispirate/cattower/infra/QueryDslSupport.kt
  src/main/kotlin/heispirate/cattower/infra/email/EmailUtility.kt
  src/main/kotlin/heispirate/cattower/scheduler/AuthCodeCleaner.kt
  src/main/resources/application.yml
Labels: :sparkles: feature

#20 Feature/#06/pet profile
  src/main/kotlin/heispirate/cattower/domain/mainUser/model/MainUser.kt
  src/main/kotlin/heispirate/cattower/domain/mainUser/repository/MainUserRepository.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/controller/PetProfileController.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/dto/PetProfileRequestDTO.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/dto/PetProfileResponseDTO.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/model/PetProfile.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/repository/PetProfileRepository.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/service/PetProfileService.kt
  src/main/kotlin/heispirate/cattower/domain/petProfile/service/PetProfileServiceImpl.kt
  src/main/kotlin/heispirate/cattower/infra/swagger/SwaggerConfig.kt
  src/test/kotlin/heispirate/cattower/adminTest/AdminRoleTest.kt
  src/test/kotlin/heispirate/cattower/petProfileTest/PetProfileTest.kt
Labels: :sparkles: feature
